FROM centos:7.4.1708
RUN yum -y install epel-release
RUN yum -y install python-pip
RUN yum clean all
RUN pip install Flask
RUN pip install Flask-PyMongo
RUN pip install flask-restful
RUN pip install flask-cors
RUN pip install flask-Login
RUN pip install xlrd
RUN pip install mongoengine
RUN pip install redis